/** 公共协议消费失败回归；合成字节不冒充原生验收。 */
import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,rm,symlink} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
import {planHash,checkTask,verifyArtifact,invalidation} from '../../runtime/craft_exchange.ts';
const sha=(value:string)=>createHash('sha256').update(value).digest('hex');
const identity=(domain='lightcraft')=>({pluginId:domain,pluginVersion:'0.1.0-test',cliVersion:'0.2.1',sha256:sha(domain),mode:'headless',capabilitySnapshotSha256:sha(domain+'capabilities')});
const policy=()=>({schemaVersion:1,runtimes:['lightcraft','designcraft','printcraft'].map(domain=>identity(domain))});
const request=(domain='lightcraft')=>{const payload={schemaVersion:'craft-native-plan/v1',plan:{domain,steps:[{command:'info',params:{}}]}};return {protocolVersion:'craft-task/v1',taskId:'task',idempotencyKey:'key',planHash:planHash(payload),inputRefs:[],expectedRevision:null,runtimeIdentity:identity(domain),authorizationRef:'explicit-fixture-scope',budget:{currency:'USD',maxMinorUnits:0,maxRevisions:2,maxExternalCalls:0},deadline:'2099-01-01T00:00:00.000Z',payload};};
const artifact=(content='fixture')=>({protocolVersion:'craft-artifact/v1',assetId:'asset',version:sha(content),sha256:sha(content),bytes:Buffer.byteLength(content),mediaType:'application/octet-stream',producerTaskId:'producer',sourceRefs:[],nativeProjectRef:null,renditions:[],dependencies:[],technicalMetadata:{},lossReportRef:null,evidenceRefs:[],location:'artifact.bin'});
const node=(id:string,dependsOn:string[]=[])=>({id,dependsOn,request:request(),inputs:[]});
test('three domains match explicit trusted identities without execution',()=>{for(const domain of ['lightcraft','designcraft','printcraft'])assert.equal(checkTask(request(domain),policy(),[]).executionAllowed,false);});
test('protocol, hash, identity, payload domain and expired deadline fail closed',()=>{for(const changed of [{protocolVersion:'craft-task/v2'},{planHash:sha('other')},{runtimeIdentity:identity('unknown')},{deadline:'2000-01-01T00:00:00.000Z'},{payload:{schemaVersion:'craft-native-plan/v2',plan:{domain:'printcraft',steps:[]}}}])assert.throws(()=>checkTask({...request(),...changed},policy(),[]));});
test('trusted policy is not optional or inferred from input',()=>{assert.throws(()=>checkTask(request(),{},[]));assert.throws(()=>checkTask(request(),{schemaVersion:1,runtimes:[]},[]));});
test('strict bool, unknown fields and unsafe nested numbers reject',()=>{assert.throws(()=>checkTask({...request(),unexpected:true},policy(),[]));assert.throws(()=>checkTask({...request(),budget:{currency:'USD',maxMinorUnits:true,maxRevisions:0,maxExternalCalls:0}},policy(),[]));assert.throws(()=>planHash({number:9007199254740992}));assert.throws(()=>planHash({number:Infinity}));});
test('input references bind identity and reject duplicate IDs and conflicts',()=>{const input=artifact(),r=request();r.inputRefs=[{assetId:input.assetId,version:input.version,sha256:input.sha256}];assert.equal(checkTask(r,policy(),[input]).executionAllowed,false);assert.throws(()=>checkTask(r,policy(),[artifact('other')]));assert.throws(()=>checkTask({...r,inputRefs:[...r.inputRefs,...r.inputRefs]},policy(),[input,input]));});
test('canonical JSON preserves JS numeric and Unicode semantics',()=>{assert.equal(planHash({n:-0}),planHash({n:0}));assert.equal(planHash({b:1e-7,a:'中文😀'}),planHash({a:'中文😀',b:0.0000001}));});
test('real files, evidence digest and containment are checked',async()=>{const root=await mkdtemp(join(tmpdir(),'craft-exchange-'));try{await writeFile(join(root,'artifact.bin'),'fixture');assert.equal((await verifyArtifact(artifact(),root)).sha256,sha('fixture'));await writeFile(join(root,'evidence.json'),'{}');const a={...artifact(),evidenceRefs:[{assetId:'evidence',version:sha('{}'),sha256:sha('{}'),location:'evidence.json'}]};await verifyArtifact(a,root);await writeFile(join(root,'evidence.json'),'changed');await assert.rejects(verifyArtifact(a,root));await assert.rejects(verifyArtifact({...artifact(),location:'../outside'},root));await symlink('/etc/hosts',join(root,'escape'));await assert.rejects(verifyArtifact({...artifact(),location:'escape'},root));}finally{await rm(root,{recursive:true,force:true});}});
test('same logical artifact version cannot change digest',async()=>{const a=artifact();assert.throws(()=>checkTask({...request(),inputRefs:[{assetId:a.assetId,version:a.version,sha256:a.sha256},{assetId:a.assetId,version:a.version,sha256:sha('other')}]},policy(),[a,{...a,sha256:sha('other')}]));});
test('payload changes invalidate only node and transitive consumers',()=>{const before=[node('photo'),node('layout',['photo']),node('pdf',['layout']),node('unrelated')],after=structuredClone(before);after[0].request.payload.plan.steps[0].params={value:1};after[0].request.planHash=planHash(after[0].request.payload);const result=invalidation(before,after,policy());assert.deepEqual(result.invalidated,['photo','layout','pdf']);assert.deepEqual(result.reusable,['unrelated']);assert.equal(result.automaticReplay,false);});
test('version and capability changes invalidate even with same payload',()=>{const before=[node('photo'),node('pdf',['photo'])],after=structuredClone(before);after[0].request.runtimeIdentity.capabilitySnapshotSha256=sha('new capabilities');const trusted=policy();trusted.runtimes.push(after[0].request.runtimeIdentity);assert.deepEqual(invalidation(before,after,trusted).invalidated,['photo','pdf']);});
test('cycles, duplicate edges, missing dependencies and removed nodes reject',()=>{for(const graph of [[node('a',['b']),node('b',['a'])],[node('a',['b','b']),node('b')],[node('a',['missing'])]])assert.throws(()=>invalidation(graph,graph,policy()));assert.throws(()=>invalidation([node('a'),node('b')],[node('a')],policy()));});
test('scheduling metadata alone does not invalidate unchanged native content',()=>{const before=[node('photo')],after=structuredClone(before);after[0].request.taskId='new-task';after[0].request.idempotencyKey='new-key';after[0].request.deadline='2099-01-02T00:00:00.000Z';assert.deepEqual(invalidation(before,after,policy()).invalidated,[]);});

test('duplicate JSON fields and escaped equivalent keys reject',async()=>{const {parseUnique}=await import('../../runtime/craft_exchange.ts');assert.throws(()=>parseUnique('{"a":1,"a":2}'));assert.throws(()=>parseUnique('{"a":1,"\\u0061":2}'));assert.equal(parseUnique('{"nested":[{"a":1},{"a":2}]}').nested.length,2);});
test('same asset version cannot silently change between graph revisions',()=>{const input=artifact(),before=[node('photo')];before[0].inputs=[input];before[0].request.inputRefs=[{assetId:input.assetId,version:input.version,sha256:input.sha256}];const after=structuredClone(before);after[0].inputs[0].sha256=sha('modified');after[0].request.inputRefs[0].sha256=sha('modified');assert.throws(()=>invalidation(before,after,policy()),/artifact_version_conflict/);});
